apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: iput-kernel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-container
        image: nodejs-app-image:latest
        ports:
        - containerPort: 3000