name: Deploy with Docker Compose

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Setup known_hosts
      run: |
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Deploy with Docker Compose
      run: |
        ssh bitcat@www.iput-kernel.com "cd /opt/iput-kernel/foundation-backend && git fetch origin main && git reset --hard origin/main && docker compose up -d --build"