name: ESLint

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Navigate to project directory
        run: cd /home/runner/work/foundation-backend/

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and Prettier
        run: npm run lint && npm run formatter

